package tn.esprit.pi.entities;

public enum TypeOffre {
    DEVELOPPEMENT,
    CLOUD,
    DATA_SCIENCE,
    CYBER_SECURITY,
    SOFTWARE_ENGINEERING,
    MACHINE_LEARNING,
    WEB_DEVELOPMENT,
    MOBILE_APP_DEVELOPMENT,
    NETWORK_ENGINEERING,
    DEVOPS
}

